### ISSUE TITLE
Subsite images too big on team page, history and gallery

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#22]
![image](https://user-images.githubusercontent.com/21954664/55167355-1ced9f80-5171-11e9-91bf-f04b3a764398.png)

They should actually be smaller like this:
![image](https://user-images.githubusercontent.com/21954664/55167396-31ca3300-5171-11e9-883e-5939c9fb4545.png)

**Comment by Zethson** [comment]
@Imipenem Didn't see on first glance why this is happening.

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/cef5ea3f6eb776109be87f17de6c30159a6f2eba and https://github.com/Zethson/igem_tuebingen_website/commit/ddc65ab52e194a5bca552109ed82b3c6d4e993aa

**Comment by Zethson** [comment]
Gap before contact us is now too big on the about_igem_team page.

Rest is fixed.

**Comment by Imipenem** [comment]
Reduced gap: see https://github.com/Zethson/igem_tuebingen_website/commit/5f35d4371972314031c27c9b8ad743749eb9cd8d
