### ISSUE TITLE
Explore whether it's possible to replace theme styles

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#26]
Some people have requested that we replace for example the blue background at the very very top of each page with a custom image. 
Is that possible?

**Comment by Zethson** [comment]
Well the HTML5UP previews have them, so somehow it should be possible I guess?

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/ac880ab52343a546e957a0f97d8d10a6be27d4fa

Added this to every subpage except for the starter page!
