### ISSUE TITLE
Explore whether it's possible to write texts next to images in the gallery

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#28]
It would be nice to add a caption or an explanation to the gallery images.

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/ae70288bdbe46f5c93b2227dfd316966259f1034 
However, the text will actually be shown inside the image at the bottom as  "caption"; with individual adjustement of font-size/color
