### ISSUE TITLE
Gallery Lightbox

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#5]
A lightbox for the gallery would be cool.
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_lightbox

**Comment by Imipenem** [comment]
Implemented  and refactored dummy gallery
See: https://github.com/Zethson/igem_tuebingen_website/commit/ffdb7f50c4d30bfb6ced2721251aa741f05be5cf
