### ISSUE TITLE
HP Subpage

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#50]
Let's add Human practices subpage.
Lina got the texts for us.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/56866178-9a0d6e00-69d6-11e9-8dff-2e54501a306a.png)

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/113c4c563f21af1a12c74b10ed31ab508673f61b
Will add an image for index-page asap.

**Comment by Imipenem** [comment]
see https://github.com/Zethson/igem_tuebingen_website/commit/b6b4819861475cc46213c3760f342e3c480c24eb

Will add an image for index-page asap.
