### ISSUE TITLE
Implement survey feature

### ISSUE THREAD

**Issue by Imipenem** [Zethson/igem_tuebingen_website#51]
We should implement the survey on our website and sending the results per email in JSON/CSV format.

- [ ] Implement the survey (using pagination, maybe like 5 questions per page???)

- [ ] Parse the data to a file in JSON/CSV? - format and send it via email

- [ ] Add a DSGVO

- [ ] Write a script, that parses and summarizes the results of each poll

- [ ] (Optional): Visualize some results/data on the website using D3

**Comment by Zethson** [comment]
Ensure that the script fetches the files from the attachments of the emails that are sent to us.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/56866162-84984400-69d6-11e9-9c5f-570edf0baa5d.png)

we can combine this with #50 .

But we can also treat it separately for now.

**Comment by Zethson** [comment]
We'll use a google form.
