### ISSUE TITLE
Resolve project 2019 conflicts with drylabs texts

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#64]
drylab stuff is twice on the project subpage.

**Comment by Imipenem** [comment]
What do you mean by twice?
I can only see one drylab section on projects subpage.

However, I should inline the second section on software page, it seems slightly outlined.

**Comment by Zethson** [comment]
The content overlaps. The last few sentences of the first paragraph are more in detail in the drylab part. They're basically repititions.  Tuesday, 07 May 2019, 07:06PM +02:00 from Imipenem  notifications@github.com :

**Comment by Imipenem** [comment]
> The content overlaps. 

Ok, it´s content related; got it.

**Comment by Imipenem** [comment]
> However, I should inline the second section on software page, it seems slightly outlined.

See https://github.com/Zethson/igem_tuebingen_website/commit/71eadfd2077d47d52e0c28e9eac02661d1f6833a for the small fix.
