### ISSUE TITLE
Sample of missing translations and smaller bugs

### ISSUE THREAD

**Issue by Imipenem** [Zethson/igem_tuebingen_website#66]
A TODO - list for the last few missing translations and/or bugs:

- [x] Missing footer translations: Team page, software and gallery subpages

- [x] Missing "Get in touch" section translations: Software, sponsors subpages

- [x] Missing title translations: Get involved, history, sponsors and gallery subpages

- [x] Project page: Drylab section too close to GMOs section

- [x] Sponsors page: Add line return between text section and download link

- [x] Some minor typos and missing points; I will add them.

**Comment by Zethson** [comment]
"Project page: Drylab section too close to GMOs section"

Got some ideas for this?

Just a few <br> won't cut it I guess?

**Comment by Imipenem** [comment]
Yes; we may exclude this Text section from the ul wrapper.

Otherwise , it may be due to some missing or miss-closed p tag, because it worked before  the latest commits

**Comment by Zethson** [comment]
Let's try this. Sounds like a good idea.

**Comment by Imipenem** [comment]
> Yes; we may exclude this Text section from the ul wrapper.
> 
> Otherwise , it may be due to some missing or miss-closed p tag, because it worked before the latest commits

Got it; it´s because of the caption above (it´s too long).

Ok, so we will replace the captions anyways and it´ll work.

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/5d59c8e8315e842495644aadab75ea155f4e6d99 for missing translations and reformatting

**Comment by Zethson** [comment]
Great! Thanks!

**Comment by Zethson** [comment]
It's difficult for me to shorten the last caption. Any alternatives?

**Comment by Imipenem** [comment]
The captions are still way too long, especially on mobile. 

A better alternative woulde be to use them as the caption of the image when its clicked using the titel attribute.
However, I´ll investigate how we can then translate them anyway.

**Comment by Imipenem** [comment]
See https://github.com/Zethson/igem_tuebingen_website/commit/dcb2f946b7a8bd282d8778bb4010015cfa041b88

Everything should be working now as intended.
