### ISSUE TITLE
SEO whole website both languages

### ISSUE THREAD

**Issue by famosab** [Zethson/igem_tuebingen_website#75]
The whole website has to be optimized for search engines.
This is a lot of work and should be done stepwise subpage by subpage.
- [ ] Home
- [ ] About
- [ ] Get Involved
- [ ] History
- [ ] Human Practices
- [ ] Project 2019
- [ ] Software
- [ ] Sponsors
- [ ] Sustainable Development
- [ ] Gallery

Check https://old.reddit.com/r/Entrepreneur/comments/4wbdcz/seo_is_not_hard_a_stepbystep_seo_tutorial_for/?st=jwumoxgi&sh=b93d07b8 for How-To.

**Comment by famosab** [comment]
Add meta-tags to all subpages

**Comment by marki155** [comment]
more proposals for the home site title are needed. Our website has not a chance to compete with keywords like "igem tübingen" or "igem glp.exe tübingen".

**Comment by Zethson** [comment]
I still feel like this is very core to us. Not sure whether we have any other options here...
