### ISSUE TITLE
Refactoring menu into menu.html broke mobile usability

### ISSUE THREAD

**Issue by Zethson** [Zethson/igem_tuebingen_website#84]
Google complains about:

'content wider than screen' and 'clickable elements too close together'.

I'm not sure why the refactoring broke this.

Any idea @marki155 @Imipenem @famosab ?

**Comment by Zethson** [comment]
It works for most sites, but not for 
about_igem_teamtuebingen
project_2019

**Comment by Zethson** [comment]
I hope that this is just the google indexer bugging out...

I've request reindexing, but am not sure whether this will fix it.

edit: for some reason the tests (https://search.google.com/test/mobile-friendly) don't seem to be able to load all page resources such as css files and so on...

**Comment by famosab** [comment]
maybe something happened when I inserted the link to the educational page? But I did not change anything on the about page

**Comment by Imipenem** [comment]
> edit: for some reason the tests (https://search.google.com/test/mobile-friendly) don't seem to be able to load all page resources such as css files and so on...

It isn´t able to load only one resources now : _https://igem-tuebingen.com/static/images/bg.jpg_ (this does simply not exist; we should delete it from source code ;))

However another test a few minutes ago stated, that it wasn´t able to load the _main.js file_ (altough everything worked as intended...);


> Google complains about:
> 
> 'content wider than screen' and 'clickable elements too close together'.
> 
> I'm not sure why the refactoring broke this.

This may be the case when some css or other files don´t load properly. Does the issue still exists and are there any more error messages or similar?
Cause at first glance the site looks as always...

**Comment by Zethson** [comment]
Just like we discussed yesterday, the spiders are likely simply broken:

```
 You requested that Google validate your fix of Mobile Usability issues on site igem-tuebingen.com. The fix requested was for the following issue: 'Clickable elements too close together'.

However, we found that some pages are still affected by this issue.
As part of the validation progress we were able to verify that 1 pages on your site are no longer affected by this issue. 
```

**Comment by Zethson** [comment]
Issue is persistent.

Let's discuss this after your exams @Imipenem . 
If we still have no idea I will contact Google. Although, I suspect that I'll just be greeted with useless bots.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/62127020-5d049080-b2d1-11e9-82d3-f0d1ed5dde30.png)

I guess the spiders got their shit together and did their work properly.
